---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
       name: nginx
    spec:
      containers:
        - name: nginx
          image: concretecristiantrucco/desafio_nginx:1.0  
          ports:
            - containerPort: 80
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: application-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
       name: application
    spec:
      containers:
        - name: application
          image: concretecristiantrucco/application:1.0
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
       name: mysql
    spec:
      containers:
        - name:  mysql
          image: concretecristiantrucco/desafio_mysql:1.0  
          ports:
            - containerPort: 3306
