apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    name: nginx-deployment
    app: application-deployment
    tier: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: application
spec:
  type: NodePort
  ports:
   - protocol: TCP
     port: 8080
     targetPort: 8080
     nodePort: 30080
  selector:
    name: application-deployment
---

apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    name: mysql-deployment
    app: application-deployment
    tier: mysql
