apiVersion: v1
kind: Service
metadata:
  name: service-nginx
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    name: nginx-deployment
---
apiVersion: v1
kind: Service
metadata:
  name: service-application
spec:
  type: NodePort
  ports:
    - port: 8080
  selector:
    name: application-deployment
---

apiVersion: v1
kind: Service
metadata:
  name: service-mysql
spec:
  type: NodePort
  ports:
    - port: 3306
  selector:
    name: mysql-deployment